# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  -
    id: "mkcert-delux"
    binary: mkcert-delux
    main: .main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
archives:
  -
    id: mkcert-delux-binaries
    name_template: "mkcert-delux-{{ .Os }}_{{ .Arch }}_{{ .Version }}"
    files:
      - LICENSE.md
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
nfpms:
  -
    file_name_template: "mkcert-delux_package_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Michael Paepcke
    homepage: https://paepcke.de/mkcert-delux
    maintainer: Michael Paepcke <git@paepcke.de>
    description: mkcert-delux
    license: BSD 3-Clause
    formats:
      - deb
      - rpm
